jamesarosen/ember-i18n

package.json
npm (which gets auto-corrected to "nom", which I almost don't want to fix) doesn't like packages without repository fields in their package.json. jshint 2.0.x didn't have that field; it's been added since then, so an update gets rid of that annoying (but harmless) warning.
Reference: http://stackoverflow.com/q/16827858/306084
=> Updating jshint version squashes npm warning

README.md, lib/ember-addon/blueprints/ember-i18n/index.js, lib/ember-addon/index.js, package.json
This is a continuation of @chrmod 's work in PR #149. I've rebased it on master and removed the configuration block (because the specified flags are no longer needed). I'm fiddling with installing it in a fork of our app to confirm that it works as advertised, but it seems to install properly.
To try it out: check out this branch into a directory, then run
> `$ npm install /path/to/ember-i18n/ --save-dev`
> `$ ember generate ember-i18n`
It will grab ember-i18n from Bower, so (perhaps ironically) version 2.9 will be installed.
=> Minimal ember-cli addon

README.md, lib/i18n.js, spec/tSpec.js
With this change, the `Ember.I18n.missingMessage` function receives a second argument that is the context passed to the `t` function. This way, in your missing message, you can spit out the data that was supposed to be interpolated in the translation.
I moved some logic around to get access to the context – I'm pretty sure the result is equivalent, and it still passes all the tests. One question I had is whether it's intentional that `missingMessage` is not documented in the README (perhaps because 3.0 is still "beta"). If desired, I'd be happy to add this documentation.
=> Support passing the context to missingMessage

lib/i18n.js, spec/tSpec.js
Fixing a bug that I introduced while adding the "missing message context" feature. The first time `t` was called with a missing key, it would mistakenly cache the context of that call and pass it to all subsequent `missingMessage` calls, even when `t` was later called with the same key but a different context.
This has minor performance implications, since the "missing function" for a given key is now regenerated every time `t` is called with that key. I couldn't immediately think of a better way to fix the problem, and hopefully no one is relying too much on the performance of the missing-translation handler anyway.
=> Fix bug with "sticky" missing message context

lib/i18n.js, spec/tSpec.js
Wrap the translated text in directional unicode characters to help with right-to-left text rendering.
=> add rtl markers if I18n.rtl is set

lib/i18n.js, spec/translateablePropertiesSpec.js
https://github.com/jamesarosen/ember-i18n/issues/198
When including TranslateableProperties in ObjectControllers, setting
properties to their translations fail because the model (ie content)
isn't available. This change schedules this work in the afterRender queue so
that models are guaranteed to be set on the controller.
=> Schedule setting up observers in afterRender queue

lib/i18n.js
My use case centers on passing a translateable
property to a component, such as the prompt for a select dropdown.
Putting this work in the `afterRender` queue will not cause the
translations to be loaded before rendering. Hence, this work belongs in
the `render` queue.
=> Add translation observers in render queue

lib/i18n.js
With EmberCLI 0.2.2+ [ember-disable-prototype-extensions is included by default](http://www.ember-cli.com/#section-1), so we cannot assume them to be there anymore.
=> Do not assume there's prototype extension

addon/macro.js
`this.i18n` must go through Ember.get since `Ember.inject.service` is lazy.  Could be an issue for those that inject the service with `i18n: Ember.inject.service()` since you've documented it here:
https://github.com/jamesarosen/ember-i18n/commit/12e56e755ac376d4e716dee1931cbc68bfac0661#diff-04c6e90faac2675aa89e2176d2eec7d8R85
=> i18n must go through Ember.get since Ember.inject.service is lazy

addon/macro.js, tests/unit/macro-test.js
While we're here, change `var` to `const` and `this.get('i18n')` to `get(this, 'i18n')` for improved safety and consistency.
Fixes #221
=> t macro works with no interpolations map

README.md
This bite me yesterday. 
Since the order of the initializers is not enforced, some could do translations and other couldn't because the locale was not defined yet.
=> Explain that you can't translate until `ember-i18n` initializer runs

README.md, app/instance-initializers/ember-i18n.js
Instead, recommend `i18n: Ember.inject.service()` or declaring your own injections in an instance-initializer.
Closes #226
Closes #234
See also #229
=> Don't auto-inject i18n into routes, controllers, components

.travis.yml, addon/add-translations.js, addon/locale.js, tests/dummy/config/environment.js
Previously, we were looking up `translations:locales/en`. That works with `podModulePrefix` unset, but breaks with it set. Instead, we turn the lookup string around: `locale:en/translations`.
This adds an additional test run with `podModulePrefix` set to `dummy/pods`.
Resolves #241
=> support podModulePrefix

README.md
My simple rule of thumb for when to use an initializer vs an instance initializer is: 
* when I need to setup things for lookup at a later time, use an initializer
* when I need to look something up and perform operations on it, use an instance initializer
*tldr;* All factories and injection rules should be done before instance initializers are ran (so that they can look things up properly).
=> Swap injection info to initializer in README.

.jshintrc, README.md, addon/get-locales.js, addon/service.js, tests/unit/locales-test.js
A result of #247. Adds a way to get a list of the added locales. Useful for rendering this list to a template to switch locales.
=> [Feature] add locales CP to the service

addon/get-locales.js, addon/legacy-helper.js, addon/locale.js, addon/macro.js
Using `Ember.keys` is deprecated, see https://github.com/emberjs/ember.js/commit/1ed73ac3d1c218b9a3b56640543fd13d0913d27e.
=> Replaced calls to the deprecated Ember.keys function with Object.keys

addon/config/en.js, addon/config/fr.js, addon/config/hi.js, addon/config/ru.js, addon/config/zh.js, addon/locale.js
The new `Locale#_setConfig` introduced in #263 relies on *some* config in the path defining `rtl`. If it's `undefined`, `_setConfig` now emits a warning. Previously, we were relying on `undefined` being falsy, but we need to specify a value (`false`) to prevent the warning. We define `rtl: false` for en, fr, hi, ru, and zh. All other included locales either define `rtl: true` or inherit from one of these.
Additionally, the warnings added in #263 used ES6 string interpolation, but didn't have the correct ES6 string syntax. This corrects that, which makes for better error messages.
=> Improve config-missing warnings

test-support/helpers/ember-i18n/test-helpers.js, tests/.jshintrc, tests/acceptance/test-helpers-test.js, tests/helpers/start-app.js
@jamesarosen Adds some test helpers that can be imported into any app that uses the add-on.
To use in an app,  in `tests/helpers/start-app.js` add this line: 
`import './ember-i18n/test-helpers';`
You can use the `t` helper like this:  ``find(`.header:contains(${t('welcome_message')})`)``
and the `expectTranslation` helper like this: `expectTranslation('.header', 'welcome_message');`
[blog post](http://williamsbdev.com/posts/Ember-CLI-test-support/) about including test helpers in the `test-support` directory.
After this is merged I'll add some documentation to the wiki.
=> add test helpers

addon/services/i18n.js, app/instance-initializers/ember-i18n.js, tests/unit/i18n-t-test.js
Set default locale on Service init, not in an initializer
`on('init')` runs whenever you construct an instance, not just when the app boots. That makes the service *slightly* more usable in things like unit tests.
=> Init Locale in Service

addon/stream.js, addon/utils/get-locales.js, addon/utils/macro.js, tests/unit/utils/locale-test.js, tests/unit/utils/macro-test.js
* Fix `locales` test intermittent failures by sorting the locales
* Fix ember-i18n on Ember 2.2 beta by reworking the private `Stream` import
* Add `i18n.locale` to the list of dependencies for properties defined via the `t` macro.
=> t macro properties observe locale

addon/services/i18n.js, addon/stream.js, app/instance-initializers/ember-i18n.js
The only time that the `service:i18n` needs to expose a `localeStream` is when we're using the legacy helper (Ember 1.12). Therefore, instead of always having the service build that Stream, we use the initializer to set it up only when we're installing the legacy helper. This makes the library completely streamless on Ember 1.13+.
=> remove Stream awareness from service:i18n

addon/services/i18n.js, addon/utils/locale.js
* `util:locale`: destructure Ember imports
* `util:locale`, `service:i18n`: pass third argument to `Ember.warn` to make Ember 2.1+ happy
=> pass ID to Ember.warn

.travis.yml, config/ember-try.js
* Add Ember 2.0.0 to CI (not currently being tested because release is 2.1).
* Add Ember 2.1.0 to CI explicitly (when Ember 2.2.0 ships this week 2.1 will no longer be tested by CI without this change).
* Update resolutions for earlier versions (can't use `release` as a resolution for 1.12 etc).
=> Update ember-try configuration.

addon/services/i18n.js, addon/utils/add-translations.js, addon/utils/locale.js, app/instance-initializers/ember-i18n.js, bower.json, package.json
As of Ember 2.3, using `this.container` from within an instance that is looked up from the container will issue a deprecation warning suggesting that you should refactor away from the private `this.container` usage to the new public API for using container/registry features (`Ember.getOwner(this)`).
This change pulls in the `ember-getowner-polyfill` to allow us to use `getOwner` on all Ember versions (tested back to 1.10 in that addon's CI).
=> Use public API for container / registry functions.

addon/utils/add-translations.js, addon/utils/locale.js, tests/helpers/start-app.js
Hi, this is a fix for the deprecation of Ember.merge:
DEPRECATION: Usage of `Ember.merge` is deprecated, use `Ember.assign` instead. [deprecation id: ember-metal.merge]
More info: https://github.com/emberjs/ember.js/pull/12303
=> Fix deprecation warning Ember.merge > Ember.assign for ember@2.5.0

index.js
This flag can be found/identified by other addons to provide a better experience.  
For example, ember-cli-template-lint would like to provide a warning when templates use "bare strings" (non-translated strings) for projects that are using a localization framework.
When a localization framework is present, and the `bare-strings` rule is not listed in the `.template-lintrc.js` file, a warning will be issued saying:
```
The `bare-strings` rule must be configured when using a localization framework (`ember-i18n`). To prevent this warning, add the following to your `.template-lintrc.js`:
rules: {
'bare-strings\': true
}
```
When `ember install ember-cli-template-lint` is ran for the first time in a project that is already using a localization framework, the proper `.template-lintrc.js` file …
=> Add `isLocalizationFramework` flag.

addon/stream.js
As of v2.7, Streams are moved to `ember-htmlbars`, we need to check if `ember-metal/streams/stream` exists.
=> Import Stream from `ember-htmlbars/streams/stream` on Ember canary

addon/services/i18n.js, tests/unit/i18n-t-test.js
Based on our discussion over slack /cc @jamesarosen 
This is for handling deprecations ahead of 5.x
Loosely related to #377
=> Reserve locale and htmlSafe attributes

addon/services/i18n.js, tests/unit/i18n-exists-test.js
Hey!
We've been hitting this issue which causes an infinite loop when trying to do fallback lookups.  :cry: 
Basically, when you hit a missing translation the system defines a translation with the _isMissing flag. Exists needs to check that flag.
Cheers!
=> exists returns true when checked twice

addon/utils/i18n/compile-template.js, package.json, tests/unit/utils/i18n/default-compiler-test.js
Using `Ember.Handlebars.SafeString` is deprecated in Ember 2.8. See: http://emberjs.com/deprecations/v2.x/#toc_use-ember-string-htmlsafe-over-ember-handlebars-safestring
A few notes. `Ember.String.htmlSafe` has existed since pre-1.0.0 so there should no concern of backwards compat. Second, the polyfill for `Ember.String.isHtmlSafe` is only used by the tests so it only needs to be a `devDependency`.
=> Use `Ember.String.htmlSafe` instead of `new Ember.Handlebars.SafeString`.

addon/services/i18n.js
This resolves deprecation warnings seen with Ember >= 2.2 and ~~ember-i18n >= 4.2.2~~ ember-i18n > 4.2.2. 
This deprecate was originally added via #381. In that PR it was stated the deprecation was targeted at 5.x. So I made the `until` value reflect that (see diff).
=> Added an `until` property when calling `Ember.deprecate`

addon/services/i18n.js
With Glimmer2, Ember.Helpers will receive their `namedArgs` as an EmptyObject. This created a problem using `hasOwnProperty` in the service. This is a simple work around.
See: https://github.com/emberjs/ember.js/issues/14161
=> Fixing new issue with Ember 2.9

addon/initializers/ember-i18n.js, addon/instance-initializers/ember-i18n.js, app/initializers/ember-i18n.js, app/instance-initializers/ember-i18n.js
The removal of the ember-i18n initializer had unseen consequences for
applications that were injecting the i18n service into other areas of
the application, as recommended by documentation in the project's wiki
(https://github.com/jamesarosen/ember-i18n/wiki/Doc:-i18n-Service).
As per the discussion in GH-31 this adds a no-op initializer back into
the code base to prevent breaks for applications injecting the i18n
service as per the wiki.
=> GH-403: Add no-op ember-i18n initializer

index.js
Fixes `Could not find module ember-htmlbars/streams/stream` error. Config callback caused `hasEmberHelper` to be set to `undefined`.
Fixes #401
=> Check ember version during init callback

addon/helper.js
- Ember docs state that computed properties that are not consumed will not trigger observers, unfortunately this is not true for readOnly properties due to a current bug in ember emberjs/ember.js#9265
- Update the i18n helper to not observe a readOnly computed property for when this issue is eventually fixed
=> Do not observe computed properties that are not consumed

addon/services/i18n.js, package.json
An update to the `ember-getowner-polyfill` caused deprecations to be spewed in my builds. Fixing that. See: https://github.com/rwjblue/ember-getowner-polyfill/issues/5 .
=> Updated the usage of `ember-getowner-polyfill` to fix deprecation

index.js, package.json
This PR updates ember-cli-version-checker to support newer ember versions that use ember-source.
=> Use VersionChecker's forEmber to support ember-source

addon/services/i18n.js, addon/utils/add-translations.js, addon/utils/locale.js
This removes deprecations and should have a very positive perf outcome in Ember 2.12
=> Use owner.factoryFor is present

addon/utils/locale.js
Also exit early if `this.rtl` and `this.pluralForm` exist, to avoid calling `factoryFor` unnecessarily.
Fixes #440
=> Check if the factoryFor ember-i18n@config:zh is null before accessing it

addon-test-support/-private/assert-translation.js
@jamesarosen I think I made a mistake in the original PR.  Maybe `textContent` would be better.  Plus stuff like `&` and such would be parsed differently.
=> use textContent instead of innerHTML

Changelog.md, addon/utils/locale.js, package-lock.json, package.json, tests/dummy/app/locales/en/translations.js, tests/unit/i18n-t-test.js
To support a default locale fallback I've added a configuration named `defaultFallback` that when configured as `true` allows i18n to provide translations that might be absent from the configured/active locale. This fallback locale is taken directly from the current i18n configuration named `defaultLocale` (as this would make the most sense and avoids yet another config option).
PR covers the basics but I'm open to feedback! Thanks again for providing this great OSS addon!
cc @jamesarosen @snewcomer
=> FEATURE: add default locale fallback
